"""add phone_number column

Revision ID: 485c25c0c5a5
Revises: 1b815638b8d3
Create Date: 2026-01-17 13:43:54.061488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '485c25c0c5a5'
down_revision: Union[str, Sequence[str], None] = '1b815638b8d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('details', sa.Column('phone_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('details', 'phone_number')
    
    # ### end Alembic commands ###
